### ISSUE TITLE
Create --help and fix sintax

### ISSUE THREAD

**Issue by edmael** [zvyn/pacfolder#1]
Hi,
I tried to run pacfolder with --help option, but instead of giving me an help or something similar it just created all the "app folder" in /home with --help prefix.

I think it will be nice to add an help with the correct syntax.

Thanks ;)

**Comment by zvyn** [comment]
Thanks for the report, the above commit also implements '-h'.

**Comment by edmael** [comment]
No problem, thanks for your help!
